In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from scipy.interpolate import interp1d
import numpy as np

pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv("2022_batters_jan4.csv")

In [6]:
df.head()

,idfangraphs,mlbid,Name,Year,Team,age,wOBA,AVG,OBP,SLG,PA,AB,R,H,S,D,T,HR,RBI,SB,CS,BB,SO
0,20123,665742.0,Juan Soto,2022,WSN,24,0.448,0.322,0.441,0.579,641,494,109,159,95,30,2,31,101,12,4,120,106
1,10155,545361.0,Mike Trout,2022,LAA,31,0.415,0.283,0.391,0.568,529,428,83,121,65,23,3,31,82,6,2,77,119
2,11579,547180.0,Bryce Harper,2022,PHI,30,0.409,0.282,0.392,0.545,633,510,96,144,76,34,2,32,89,14,3,98,140
3,19709,665487.0,Fernando Tatis Jr.,2022,SDP,23,0.403,0.291,0.369,0.576,631,550,110,160,86,31,3,40,103,24,5,66,156
4,5361,518692.0,Freddie Freeman,2022,FA,33,0.400,0.300,0.389,0.525,612,514,100,154,94,31,2,27,90,6,2,78,105

In [3]:
# points league settings

b1_points = 1
b2_points = 2
b3_points = 3
hr_points = 4
sb_points = 1
r_points = 1
rbi_points = 1
bb_points = 1
so_points = -1

In [16]:
def calculate_hitting(b1, b2, b3, hr, sb, r, rbi, bb, so, b1_points = 1, b2_points = 2, b3_points = 3, hr_points = 4, sb_points = 1, r_points = 1, rbi_points = 1, bb_points = 1, so_points = -1):
    return ((int(b1) * b1_points) + 
            (int(b2) * b2_points) + 
            (int(b3) * b3_points) + 
            (int(hr) * hr_points) + 
            (int(sb) * sb_points) +
            (int(r) * r_points) +
            (int(rbi) * rbi_points) +
            (int(bb) * bb_points) +
            (int(so) * so_points))

In [17]:
df['FantasyPoints_Hitting'] = df.apply(lambda x: calculate_hitting(x.S, 
                                                                   x.D,
                                                                   x['T'],
                                                                   x.HR,
                                                                   x.SB,
                                                                   x.R,
                                                                   x.RBI,
                                                                   x.BB,
                                                                   x.SO,
                                                                   b1_points,
                                                                   b2_points,
                                                                   b3_points, 
                                                                   hr_points,
                                                                   sb_points, 
                                                                   r_points, 
                                                                   rbi_points, 
                                                                   bb_points, 
                                                                   so_points),axis=1)

In [18]:
df['FantasyPoints_Hitting']

0      521
1      373
2      435
3      464
4      439
      ...
335    197
336    153
337    134
338     92
339    152
Name: FantasyPoints_Hitting, Length: 340, dtype: int64

In [27]:
budget = 260
min_bid = 1
teams = 12
players = 20
avg_budget = budget / players
tot_players = teams * players

print(avg_budget)
print(tot_players)

13.0
240

In [28]:
df = df.sort_values(by = 'FantasyPoints_Hitting', ascending= False)

df_top = df.head(tot_players)
df_top

,idfangraphs,mlbid,Name,Year,Team,age,wOBA,AVG,OBP,SLG,PA,AB,R,H,S,D,T,HR,RBI,SB,CS,BB,SO,FantasyPoints_Hitting
0,20123,665742.0,Juan Soto,2022,WSN,24,0.448,0.322,0.441,0.579,641,494,109,159,95,30,2,31,101,12,4,120,106,521
12,13510,608070.0,Jose Ramirez,2022,CLE,30,0.375,0.267,0.348,0.521,644,559,99,149,78,35,4,33,100,23,5,69,104,479
3,19709,665487.0,Fernando Tatis Jr.,2022,SDP,23,0.403,0.291,0.369,0.576,631,550,110,160,86,31,3,40,103,24,5,66,156,464
6,19611,665489.0,Vladimir Guerrero Jr.,2022,TOR,23,0.388,0.293,0.371,0.525,658,577,98,169,103,32,3,32,96,4,1,69,109,462
7,16252,607208.0,Trea Turner,2022,LAD,29,0.383,0.310,0.366,0.519,656,594,105,184,117,36,5,26,81,29,6,50,116,457
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271,15191,640461.0,Chad Pinder,2022,OAK,30,0.314,0.243,0.303,0.411,485,440,60,107,64,27,1,15,59,2,1,35,115,222
251,12434,607680.0,Kevin Pillar,2022,FA,33,0.318,0.255,0.301,0.427,428,396,55,101,64,20,3,14,53,7,3,21,83,222
245,15487,622682.0,Victor Reyes,2022,DET,28,0.319,0.269,0.313,0.412,482,449,60,121,85,21,5,11,44,12,3,27,107,222
250,11476,546318.0,Odubel Herrera,2022,FA,31,0.318,0.252,0.309,0.411,446,404,52,102,64,24,2,12,48,6,2,31,82,221
212,2396,467793.0,Carlos Santana,2022,KCR,36,0.325,0.228,0.335,0.382,421,356,51,81,53,13,0,14,48,2,0,58,73,221

In [29]:
minimum = min(df_top['FantasyPoints_Hitting'])

maximum = max(df_top['FantasyPoints_Hitting'])

std = df_top['FantasyPoints_Hitting'].std()

mean = df_top['FantasyPoints_Hitting'].mean()

print(std)
print(mean)

58.53629326332305
309.73333333333335

In [30]:
def max_std(std, mean, maximum):
    i = 1
    j = 0
    while i > 0:
        if (maximum > mean + (j * std)) & (maximum < mean + (i * std)):
            return i
        else:
            i += 1
            j += 1

sd_above = max_std(std, mean, maximum)
print(sd_above)

4

In [31]:
m = interp1d([minimum,maximum],[min_bid,avg_budget*sd_above])

df_top['auction$'] = round(df_top['FantasyPoints_Hitting'].apply(m), 1)

/var/folders/ly/7vdr23qj7yn96w59b90h_zmm0000gn/T/ipykernel_43203/3197369051.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_top['auction$'] = round(df_top['FantasyPoints_Hitting'].apply(m), 1)

In [32]:
df_top

,idfangraphs,mlbid,Name,Year,Team,age,wOBA,AVG,OBP,SLG,PA,AB,R,H,S,D,T,HR,RBI,SB,CS,BB,SO,FantasyPoints_Hitting,auction$
0,20123,665742.0,Juan Soto,2022,WSN,24,0.448,0.322,0.441,0.579,641,494,109,159,95,30,2,31,101,12,4,120,106,521,52.0
12,13510,608070.0,Jose Ramirez,2022,CLE,30,0.375,0.267,0.348,0.521,644,559,99,149,78,35,4,33,100,23,5,69,104,479,44.9
3,19709,665487.0,Fernando Tatis Jr.,2022,SDP,23,0.403,0.291,0.369,0.576,631,550,110,160,86,31,3,40,103,24,5,66,156,464,42.3
6,19611,665489.0,Vladimir Guerrero Jr.,2022,TOR,23,0.388,0.293,0.371,0.525,658,577,98,169,103,32,3,32,96,4,1,69,109,462,42.0
7,16252,607208.0,Trea Turner,2022,LAD,29,0.383,0.310,0.366,0.519,656,594,105,184,117,36,5,26,81,29,6,50,116,457,41.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271,15191,640461.0,Chad Pinder,2022,OAK,30,0.314,0.243,0.303,0.411,485,440,60,107,64,27,1,15,59,2,1,35,115,222,1.2
251,12434,607680.0,Kevin Pillar,2022,FA,33,0.318,0.255,0.301,0.427,428,396,55,101,64,20,3,14,53,7,3,21,83,222,1.2
245,15487,622682.0,Victor Reyes,2022,DET,28,0.319,0.269,0.313,0.412,482,449,60,121,85,21,5,11,44,12,3,27,107,222,1.2
250,11476,546318.0,Odubel Herrera,2022,FA,31,0.318,0.252,0.309,0.411,446,404,52,102,64,24,2,12,48,6,2,31,82,221,1.0
212,2396,467793.0,Carlos Santana,2022,KCR,36,0.325,0.228,0.335,0.382,421,356,51,81,53,13,0,14,48,2,0,58,73,221,1.0